from target_extraction.allen import dataset_readers
from target_extraction.allen import models
from target_extraction.allen import modules
from target_extraction.allen import predictors
from target_extraction.allen import token_indexers
from target_extraction.allen.allennlp_model import AllenNLPModel